(ns crux.internal.keys)

(defonce CRUX-PROPERTIES :crux/properties)
(defonce COMMAND-CONSTRAINT-FORMS :command-constraint-forms)
(defonce COMMAND-VALIDATION-FORMS :command-validation-forms)
(defonce COMMAND-VALIDATIONS :command-validations)
(defonce REDUCER :reducer)
(defonce REDUCE-FORMS :reduce-forms)
(defonce ADDITIONAL-EVENT-ATTRS :additional-event-attrs)
(defonce CONSTRAINTS :constraints)
(defonce VALIDATIONS :validations)
(defonce FIELDS :fields)
(defonce ENTITIES :entities)
(defonce EVENTS :events)
(defonce EVENT-SYMBOL :event-symbol)
(defonce COMMAND-SYMBOL :command-symbol)
(defonce DEFAULTS :defaults)
(defonce PROPERTIES :properties)
(defonce PROPERTY-FORMS :property-forms)
(defonce COMMAND-CONSTRAINTS :command-constraints)
(defonce COMMAND-VALIDATORS :command-validators)
(defonce ID-FIELD :id-field)


